<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Proplayer_model extends CI_Model
{

    public $table = 'proplayer';
    public $id = 'id_proplayer';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_proplayer', $q);
	$this->db->or_like('nama_player', $q);
	$this->db->or_like('telp_p', $q);
	$this->db->or_like('id_tim', $q);
	$this->db->or_like('id_game', $q);
	$this->db->or_like('images', $q);
	$this->db->or_like('video', $q);
	$this->db->or_like('prestasi', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lng', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->select('p.id_proplayer, p.nama_player, p.telp_p , p.images, p.video, p.prestasi, p.lat, p.lng, t.id_tim, t.nama_tim, g.id_game, g.nama_game', $q);
    $this->db->from('proplayer p');
        $this->db->join('tim t', 'p.id_tim = t.id_tim');
        $this->db->join('game g', 'p.id_game = g.id_game');
    $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function transaksi_pro($id)
    {
        $this->db->select('p.id_proplayer, p.nama_player, p.telp_p , p.images, p.video, p.prestasi, p.lat, p.lng, t.id_tim, t.nama_tim, g.id_game, g.nama_game');
        $this->db->from('proplayer p');
        $this->db->join('tim t', 'p.id_tim = t.id_tim');
        $this->db->join('game g', 'p.id_game = g.id_game');
        $this->db->where($this->id, $id);
        $query = $this->db->get()->row();
        return $query;
    }

}

/* End of file Proplayer_model.php */
/* Location: ./application/models/Proplayer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-20 09:22:29 */
/* http://harviacode.com */