<?php

use LDAP\Result;

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bom_model extends CI_Model
{

    public $table = 'bom';
    public $id = 'id_bom';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('b.id_bom,m.id_material,m.nama_material,mo.id_model,mo.nama_model,mo.keterangan,b.qty');
        $this->datatables->from('bom b');
        //add this line for join
        $this->datatables->join('tbl_material m', 'b.id_material = m.id_material');
        $this->datatables->join('tbl_model mo', 'b.id_model = mo.id_model');
        $this->datatables->add_column('action', anchor(site_url('bom/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('bom/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('bom/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_bom');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_bom()
    {
        $this->db->select('b.id_bom,m.id_material,m.nama_material,mo.id_model,mo.nama_model,mo.keterangan,b.qty');
        $this->db->from('bom b');
        $this->db->join('tbl_material m', 'b.id_material = m.id_material');
        $this->db->join('tbl_model mo', 'b.id_model = mo.id_model');
        $this->db->order_by($this->id, $this->order);         
        $query = $this->db->get(); 
        if($query->num_rows() != 0)
        {
            return $query->result();
        }
        else
        {
            return false;
        }
    }
    function get_bomid($id)
    {
        $this->db->select('b.id_bom,m.id_material,m.nama_material,mo.id_model,mo.nama_model,mo.keterangan,b.qty');
        $this->db->from('bom b');
        $this->db->join('tbl_material m', 'b.id_material = m.id_material');
        $this->db->join('tbl_model mo', 'b.id_model = mo.id_model');
        $this->db->where($this->id, $id);
        $this->db->order_by($this->id, $this->order);         
        $query = $this->db->get(); 
        // return $query->row();
        foreach ($query->result() as $row) {
            // $output = $row->id_model;
            $output = $row->id_model;
        }
        //return data kabupaten
        return $output;
    }
    function get_bomqty($id)
    {
        $this->db->select('b.id_bom,m.id_material,m.nama_material,mo.id_model,mo.nama_model,mo.keterangan,b.qty');
        $this->db->from('bom b');
        $this->db->join('tbl_material m', 'b.id_material = m.id_material');
        $this->db->join('tbl_model mo', 'b.id_model = mo.id_model');
        $this->db->where($this->id, $id);
        $this->db->order_by($this->id, $this->order);         
        $query = $this->db->get(); 
        // return $query->row();
        foreach ($query->result() as $row) {
            // $output = $row->id_model;
            $output = $row->qty;
        }
        //return data kabupaten
        return $output;
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_bom', $q);
	$this->db->or_like('id_material', $q);
	$this->db->or_like('id_model', $q);
	$this->db->or_like('qty', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_bom', $q);
	$this->db->or_like('id_material', $q);
	$this->db->or_like('id_model', $q);
	$this->db->or_like('qty', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bom_model.php */
/* Location: ./application/models/Bom_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-09 12:30:31 */
/* http://harviacode.com */