<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Material_model extends CI_Model
{

    public $table = 'tbl_material';
    public $id = 'id_material';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('m.id_material,m.nomor_material,m.nama_material,k.nama_kat_material,s.nama_supplier,m.spek_material,m.satuan,m.qty');
        $this->datatables->from('tbl_material m');
        $this->datatables->join('tbl_supplier s','s.id_supplier = m.id_supplier','left');
        $this->datatables->join('tbl_kat_material k','k.id_kat_material = m.id_kat_material','left');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_material.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('material/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('material/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('material/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_material');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_material', $q);
	$this->db->or_like('id_supplier', $q);
//	$this->db->or_like('id_model', $q);
	$this->db->or_like('id_kat_material', $q);
	$this->db->or_like('nomor_material', $q);
	$this->db->or_like('nama_material', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('spek_material', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_material', $q);
	$this->db->or_like('id_supplier', $q);
//	$this->db->or_like('id_model', $q);
	$this->db->or_like('id_kat_material', $q);
	$this->db->or_like('nomor_material', $q);
	$this->db->or_like('nama_material', $q);
	$this->db->or_like('qty', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('spek_material', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Material_model.php */
/* Location: ./application/models/Material_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-26 14:35:43 */
/* http://harviacode.com */